server:
  port: 8081
spring:
  kafka:
    producer:
      bootstrap-servers: localhost:29092
    consumer:
      group-id: group-1
      auto-offset-reset: earliest
      bootstrap-servers: localhost:29092