-- EMPLOYEE TABLE: INITIAL LOAD EXAMPLE DATA
INSERT INTO EMPLOYEE VALUES (1, 'ASampleName001','ASampleSurname001');
INSERT INTO EMPLOYEE VALUES (2, 'ASampleName002','ASampleSurname002');
INSERT INTO EMPLOYEE VALUES (3, 'ASampleName003','ASampleSurname003');