CREATE TABLE IF NOT EXISTS EMPLOYEE(
ID INT PRIMARY KEY, 
FIRST_NAME VARCHAR(255), 
LAST_NAME VARCHAR(255),
CODE VARCHAR(255),
DOB DATE);
CREATE SEQUENCE IF NOT EXISTS EMPLOYEE_SEQ INCREMENT BY 1 MAXVALUE 999999 MINVALUE 1 NOCACHE;